masterPassword: 'research_thub_password'

accounts:
  - name: 'Carol (Node C — Receiver)'
    serverUrl: 'lnd-carol:10009'
    macaroonPath: '/lnd/.lnd/data/chain/bitcoin/regtest/admin.macaroon'
    certificatePath: '/lnd/.lnd/tls.cert'
